import { useState, useEffect } from "react"
import Head from "next/head"
import Router from "next/router"

import AppLayout from "components/AppLayout"
import Button from "components/Button"
import GitHubIcon from "components/Icons/GitHub"
import Spinner from "components/Spinner"

import { colors } from "styles/theme"

import { loginWithGitHub, onUserStateChanged } from "../firebase/client"

const USER_STATES = {
  UNKNOW: undefined,
  NOT_LOGGED: null,
}

export default function Home() {
  const [user, setUser] = useState(USER_STATES.UNKNOW)

  useEffect(() => {
    onUserStateChanged(setUser)
  }, [])

  useEffect(() => {
    user && Router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGitHub()
  }

  return (
    <>
      <Head>
        <title>Nexter </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="/cubo-logo.png" alt="logo" />
          <h1>Nexter</h1>
          <h2>
            Talk about development <br /> with developers
          </h2>
          <div>
            {user === USER_STATES.NOT_LOGGED && (
              <Button onClick={handleClick}>
                <GitHubIcon fill="#fff" width={32} height={32} />
                Login with GitHub
              </Button>
            )}
            {user === USER_STATES.UNKNOW && <Spinner />}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        section {
          height: 100%;
          display: grid;
          place-content: center;
          place-items: center;
        }

        img {
          width: 120px;
        }

        div {
          margin-top: 16px;
        }

        h1 {
          color: ${colors.primary};
          font-weight: 700;
          margin-bottom: 16px;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 18px;
          margin: 0;
        }
      `}</style>
    </>
  )
}
