import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import AppLayout from '../components/AppLayout'
import {colors} from '../styles/theme'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nexter </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src='/vect-logo.png' alt='logo' />
          <h1>Nexter</h1>
          <h2>Talk about development <br /> with developers</h2>
        </section>
      </AppLayout>

      <style jsx>{`
        section {
          height: 100%;
          display: grid;
          place-content: center;
          place-items: center;
        }

        img {
          width: 120px;
        }

        h1 {
          color: ${colors.primary};
          font-weight: 800;
          margin-bottom: 16px;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 21px;
          margin: 0;
        }
      
      `}</style>
    </>
  )
}
